Added expert mode to bigBench script, added show* modules to driver

diff --git a/bin/bigBench b/bin/bigBench
--- a/bin/bigBench
+++ b/bin/bigBench
@@ -11,41 +11,68 @@
 ## function definitions
 ## ===================================================
 showGlobalHelp () {
-  echo "Usage: `basename $0` runBenchmark [options]"
-  echo
-  echo "General options:"
-  echo -e "-d\tdatabase to use (default: $BIG_BENCH_DEFAULT_DATABASE)"
-  echo -e "-e\tengine to use (default: $BIG_BENCH_DEFAULT_ENGINE)"
-  echo -e "-f\tscale factor for data set (default: $BIG_BENCH_DEFAULT_SCALE_FACTOR)"
-  echo -e "-h\tshow this help"
-  echo -e "-m\tmap tasks for data generation (default: $BIG_BENCH_DEFAULT_MAP_TASKS)"
-  echo -e "-s\tnumber of parallel streams (default: $BIG_BENCH_DEFAULT_NUMBER_OF_PARALLEL_STREAMS)"
-  echo
-  echo "Driver specific options:"
-  echo -e "-a\tdry-run - pretend command execution"
-  echo -e "-b\tprint stdout of called bash scripts during execution"
-  echo -e "-i\tphases the driver performs (see $BIG_BENCH_CONF_DIR/bigBench.properties for details on format)"
-  echo -e "-j\tqueries the driver runs (see $BIG_BENCH_CONF_DIR/bigBench.properties for details on format)"
-  echo
-  # INTERNAL USE ONLY
-  echo "WARNING"
-  echo "Options for INTERNAL USE ONLY:"
-  echo "Only set manually if you know what you are doing!"
-  echo "Ignoring them is probably the best solution"
-  echo
-  echo "Usage: `basename $0` module [options]"
-  echo
-  echo -e "-D\tquery part to debug"
-  echo -e "-p\tbenchmark phase to use (default: $BIG_BENCH_DEFAULT_BENCHMARK_PHASE)"
-  echo -e "-q\tquery number to run"
-  echo -e "-t\tstream number for query run"
-  echo -e "-v\tsql script for metastore population (default: $BIG_BENCH_POPULATE_METASTORE_FILE)"
-  echo -e "-w\tsql script for metastore refresh (default: $BIG_BENCH_REFRESH_METASTORE_FILE)"
-  echo -e "-y\tfile with additional user defined query parameters (global: $BIG_BENCH_QUERY_PARAMS_FILE)"
-  echo -e "-z\tfile with additional user defined engine settings (global: $BIG_BENCH_ENGINE_SETTINGS_FILE)"
-  echo
-  echo "List of available modules:"
-  ls -1 "$BIG_BENCH_ENGINE_BIN_DIR"
+  if [ "$BIG_BENCH_EXPERT_MODE" -eq 0 ]
+  then
+    echo "Usage: `basename $0` runBenchmark [options]"
+    echo
+    echo "General options:"
+    echo -e "-d\tdatabase to use (default: $BIG_BENCH_DEFAULT_DATABASE)"
+    echo -e "-e\tengine to use (default: $BIG_BENCH_DEFAULT_ENGINE)"
+    echo -e "-f\tscale factor for data set (default: $BIG_BENCH_DEFAULT_SCALE_FACTOR)"
+    echo -e "-h\tshow this help"
+    echo -e "-m\tmap tasks for data generation (default: $BIG_BENCH_DEFAULT_MAP_TASKS)"
+    echo -e "-s\tnumber of parallel streams (default: $BIG_BENCH_DEFAULT_NUMBER_OF_PARALLEL_STREAMS)"
+    echo
+    echo "Driver specific options:"
+    echo -e "-a\tdry-run - pretend command execution"
+    echo -e "-b\tprint stdout of called bash scripts during execution"
+    echo -e "-i\tphases the driver performs (see $BIG_BENCH_CONF_DIR/bigBench.properties for details on format)"
+    echo -e "-j\tqueries the driver runs (see $BIG_BENCH_CONF_DIR/bigBench.properties for details on format)"
+    echo
+    echo "Take a look into $BIG_BENCH_CONF_DIR/bigBench.properties for a well documented description how to configure the driver"
+    echo
+    echo "Expert mode:"
+    echo -e "-U\tunlock expert mode - WARNING: run modules manually only if you know what you are doing!"
+    echo
+  else
+    # INTERNAL USE ONLY
+    echo "Usage: `basename $0` module [options]"
+    echo
+    echo "General options:"
+    echo -e "-d\tdatabase to use (default: $BIG_BENCH_DEFAULT_DATABASE)"
+    echo -e "-e\tengine to use (default: $BIG_BENCH_DEFAULT_ENGINE)"
+    echo -e "-f\tscale factor for data set (default: $BIG_BENCH_DEFAULT_SCALE_FACTOR)"
+    echo -e "-h\tshow this help"
+    echo -e "-m\tmap tasks for data generation (default: $BIG_BENCH_DEFAULT_MAP_TASKS)"
+    echo -e "-s\tnumber of parallel streams (default: $BIG_BENCH_DEFAULT_NUMBER_OF_PARALLEL_STREAMS)"
+    echo
+    echo "Driver specific options:"
+    echo -e "-a\tdry-run - pretend command execution"
+    echo -e "-b\tprint stdout of called bash scripts during execution"
+    echo -e "-i\tphases the driver performs (see $BIG_BENCH_CONF_DIR/bigBench.properties for details on format)"
+    echo -e "-j\tqueries the driver runs (see $BIG_BENCH_CONF_DIR/bigBench.properties for details on format)"
+    echo
+    echo "Take a look into $BIG_BENCH_CONF_DIR/bigBench.properties for a well documented description how to configure the driver"
+    echo
+    echo "WARNING"
+    echo "INTERNAL USE ONLY:"
+    echo "Only set manually if you know what you are doing!"
+    echo "Ignoring them is probably the best solution"
+    echo
+    echo -e "-U\tunlock expert mode"
+    echo
+    echo -e "-D\tquery part to debug"
+    echo -e "-p\tbenchmark phase to use (default: $BIG_BENCH_DEFAULT_BENCHMARK_PHASE)"
+    echo -e "-q\tquery number to run"
+    echo -e "-t\tstream number for query run"
+    echo -e "-v\tsql script for metastore population (default: $BIG_BENCH_POPULATE_METASTORE_FILE)"
+    echo -e "-w\tsql script for metastore refresh (default: $BIG_BENCH_REFRESH_METASTORE_FILE)"
+    echo -e "-y\tfile with additional user defined query parameters (global: $BIG_BENCH_QUERY_PARAMS_FILE)"
+    echo -e "-z\tfile with additional user defined engine settings (global: $BIG_BENCH_ENGINE_SETTINGS_FILE)"
+    echo
+    echo "List of available modules:"
+    ls -1 "$BIG_BENCH_ENGINE_BIN_DIR"
+  fi
   exit 0
 }
 
@@ -196,20 +223,25 @@ fi
 ## all static settings sourced, start checking runtime settings
 ## ===================================================
 
-# the help must list the modules, so keep on parsing stuff first
-[[ $# -eq 0 || "$1" = "-h" || "$1" = "--help" ]] && SHOW_GLOBAL_HELP="1"
-
 ## ===================================================
 ## parse command line arguments
 ## ===================================================
 # the first parameter after the options must be the module name
-export MODULE_NAME="$1"
-shift
+
+# if there are no parameters or the first parameter starts with "-"
+# the user has not provided any module to run
+if [[ $# -eq 0 || "`echo "$1" | cut -c1`" = "-" ]]
+then
+  export MODULE_NAME=""
+else
+  export MODULE_NAME="$1"
+  shift
+fi
 
 export LIST_OF_USER_OPTIONS="$@"
 
 # parse remaining options
-while getopts ":d:D:e:f:hm:p:q:s:t:v:w:y:z:abi:j:" OPT; do
+while getopts ":d:D:e:f:hm:p:q:s:t:Uv:w:y:z:abi:j:" OPT; do
   case "$OPT" in
     # script options
     d)
@@ -230,7 +262,7 @@ while getopts ":d:D:e:f:hm:p:q:s:t:v:w:y:z:abi:j:" OPT; do
     ;;
     h)
       #echo "-h was triggered, Parameter: $OPTARG" >&2
-      SHOW_MODULE_HELP="1"
+      SHOW_HELP="1"
     ;;
     m)
       #echo "-m was triggered, Parameter: $OPTARG" >&2
@@ -251,6 +283,10 @@ while getopts ":d:D:e:f:hm:p:q:s:t:v:w:y:z:abi:j:" OPT; do
     t)
       #echo "-s was triggered, Parameter: $OPTARG" >&2
       USER_STREAM_NUMBER="$OPTARG"
+    ;;
+    U)
+      #echo "-U was triggered, Parameter: $OPTARG" >&2
+      USER_EXPERT_MODE="1"
     ;;
     v)
       #echo "-v was triggered, Parameter: $OPTARG" >&2
@@ -298,6 +334,9 @@ done
 
 # remove options from parameter list
 shift $((OPTIND-1))
+
+export BIG_BENCH_EXPERT_MODE="${USER_EXPERT_MODE:-"0"}"
+export SHOW_HELP="${SHOW_HELP:-"0"}"
 
 # global shared variables
 export BIG_BENCH_DATABASE="${USER_DATABASE:-"$BIG_BENCH_DEFAULT_DATABASE"}"
@@ -372,7 +411,7 @@ then
 fi
 
 # as the module's bin directory is known at this point, the help can list all modules within that directory
-[ "$SHOW_GLOBAL_HELP" = "1" ] && showGlobalHelp
+[[ "$SHOW_HELP" -eq 1 && -z "$MODULE_NAME" ]] && showGlobalHelp
 
 ## ===================================================
 ## check for module existence and correctness
@@ -382,8 +421,14 @@ if [ -f "$MODULE" ]
 then
   source "$MODULE"
 else
-  echo "Module $MODULE not found, aborting script."
-  exit 1
+  export MODULE="$BIG_BENCH_BIN_DIR/$MODULE_NAME"
+  if [ -f "$MODULE" ]
+  then
+    source "$MODULE"
+  else
+    echo "Module $MODULE not found, aborting script."
+    exit 1
+  fi
 fi
 
 # check if the module's run method was implemented properly
@@ -414,9 +459,16 @@ fi
 logEnvInformation
 
 # run module
-if [ "$SHOW_MODULE_HELP" = "1" ]
+if [[ "$BIG_BENCH_EXPERT_MODE" -eq 1 || "$MODULE_NAME" = "runBenchmark" ]]
 then
-  "$MODULE_HELP_METHOD"
+  if [ "$SHOW_HELP" -eq 1 ]
+  then
+    "$MODULE_HELP_METHOD"
+  else
+    runCmdWithErrorCheck "$MODULE_RUN_METHOD"
+  fi
 else
-  runCmdWithErrorCheck "$MODULE_RUN_METHOD"
+  echo "Running module $MODULE_NAME directly is only supported in expert mode"
+  echo "Normal mode only supports runBenchmark module"
+  exit 1
 fi
