Added initial validation support code

diff --git a/engines/hive/bin/validateQuery b/engines/hive/bin/validateQuery
--- a/engines/hive/bin/validateQuery
+++ b/engines/hive/bin/validateQuery
@@ -7,20 +7,37 @@
 #
 #No license under any patent, copyright, trade secret or other intellectual property right is granted to or conferred upon you by disclosure or delivery of the Materials, either expressly, by implication, inducement, estoppel or otherwise. Any license under such intellectual property rights must be express and approved by Intel in writing.
 
-query_run_main_method () {
-	QUERY_SCRIPT="$QUERY_DIR/$QUERY_NAME.sql"
-	if [ ! -r "$QUERY_SCRIPT" ]
-	then
-		echo "SQL file $QUERY_SCRIPT can not be read."
-		exit 1
-	fi
-
-        runCmdWithErrorCheck runEngineCmd -f "$QUERY_SCRIPT"
+helpModule () {
+  echo "This module validates all query results from HDFS as well as from the metastore for one query"
+  echo
+  echo "Options:"
+  echo -e "-q\tquery number to run (required)"
+  echo -e "-d\tdatabase to use"
+  echo -e "-h\tshow this help"
+  echo -e "-p\tbenchmark phase to use"
+  echo -e "-t\tstream number for query run"
+  echo -e "-z\tfile with user defined engine settings"
 }
 
-query_run_clean_method () {
-	runCmdWithErrorCheck runEngineCmd -e "DROP TABLE IF EXISTS $TEMP_TABLE; DROP TABLE IF EXISTS $RESULT_TABLE;"
-}
+runModule () {
+  if ! initQueryEnv
+  then
+    return 1
+  fi
 
-query_run_validate_method () {
+  echo "==============================================="
+  echo "Validating query : $QUERY_NAME"
+  echo "-----------------------------------------------"
+  echo "benchmark phase: $BIG_BENCH_BENCHMARK_PHASE"
+  echo "stream number  : $BIG_BENCH_STREAM_NUMBER"
+  echo "user parameter file: $USER_QUERY_PARAMS_FILE"
+  echo "user settings file : $USER_ENGINE_SETTINGS_FILE"
+  if [ -n "$DEBUG_QUERY_PART" ]; then
+    echo "query part to debug: $DEBUG_QUERY_PART"
+  fi
+  echo "log: $LOG_FILE_NAME"
+  echo "==============================================="
+
+  # Run the validate method implemented in the query's run.sh
+  runCmdWithErrorCheck "$QUERY_VALIDATE_METHOD"
 }
