replaced tabs with spaces in scripts to be consistent with the rest of the repository

diff --git a/scripts/bigBench b/scripts/bigBench
--- a/scripts/bigBench
+++ b/scripts/bigBench
@@ -4,231 +4,231 @@
 ENV_SETTINGS="`dirname $0`/../setEnvVars"
 if [ ! -f "$ENV_SETTINGS" ]
 then
-	echo "Environment setup file $ENV_SETTINGS not found"
-	exit 1
+  echo "Environment setup file $ENV_SETTINGS not found"
+  exit 1
 else
-	source "$ENV_SETTINGS"
+  source "$ENV_SETTINGS"
 fi
 
 # write environment information into logfile
 logEnvInformation
 
 runHiveCmd () {
-	if [ "$BINARY" = "$SHARK_BINARY" ]
-	then
-		local HIVE_PARAMS="-skipRddReload $HIVE_PARAMS"
-	fi
-	"$BINARY" $HIVE_PARAMS -i "$COMBINED_PARAMS_FILE" "$@"
+  if [ "$BINARY" = "$SHARK_BINARY" ]
+  then
+    local HIVE_PARAMS="-skipRddReload $HIVE_PARAMS"
+  fi
+  "$BINARY" $HIVE_PARAMS -i "$COMBINED_PARAMS_FILE" "$@"
 }
 
 buildCombinedParamsFile () {
-	# build combined parameter file for hive
-	if [ -r "$GLOBAL_QUERY_PARAMS_FILE" ]
-	then
-		echo "!echo settings from global parameter file: $GLOBAL_QUERY_PARAMS_FILE ;" >> "$COMBINED_PARAMS_FILE"
-		cat "$GLOBAL_QUERY_PARAMS_FILE" > "$COMBINED_PARAMS_FILE"
-	else
-		echo "Global query parameter file $GLOBAL_QUERY_PARAMS_FILE can not be read."
-		rm -rf "$COMBINED_PARAMS_FILE"
-		return 1
-	fi
+  # build combined parameter file for hive
+  if [ -r "$GLOBAL_QUERY_PARAMS_FILE" ]
+  then
+    echo "!echo settings from global parameter file: $GLOBAL_QUERY_PARAMS_FILE ;" >> "$COMBINED_PARAMS_FILE"
+    cat "$GLOBAL_QUERY_PARAMS_FILE" > "$COMBINED_PARAMS_FILE"
+  else
+    echo "Global query parameter file $GLOBAL_QUERY_PARAMS_FILE can not be read."
+    rm -rf "$COMBINED_PARAMS_FILE"
+    return 1
+  fi
 
-	if [ -r "$GLOBAL_SETTINGS_FILE" ]
-	then
-		echo "!echo settings from global settings file: $GLOBAL_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
-		cat "$GLOBAL_SETTINGS_FILE" >> "$COMBINED_PARAMS_FILE"
-	else
-		echo "Global hive settings file $GLOBAL_SETTINGS_FILE can not be read."
-		rm -rf "$COMBINED_PARAMS_FILE"
-		return 1
-	fi
+  if [ -r "$GLOBAL_SETTINGS_FILE" ]
+  then
+    echo "!echo settings from global settings file: $GLOBAL_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
+    cat "$GLOBAL_SETTINGS_FILE" >> "$COMBINED_PARAMS_FILE"
+  else
+    echo "Global hive settings file $GLOBAL_SETTINGS_FILE can not be read."
+    rm -rf "$COMBINED_PARAMS_FILE"
+    return 1
+  fi
 
-	if [[ -n "$LOCAL_HIVE_SETTINGS_FILE" && -r "$LOCAL_HIVE_SETTINGS_FILE" ]]
-	then
-		echo "!echo settings from local settings file: $LOCAL_HIVE_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
-		cat "$LOCAL_HIVE_SETTINGS_FILE" >> "$COMBINED_PARAMS_FILE"
-	else
-		echo "!echo no settings from local settings file: $LOCAL_HIVE_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
-	fi
+  if [[ -n "$LOCAL_HIVE_SETTINGS_FILE" && -r "$LOCAL_HIVE_SETTINGS_FILE" ]]
+  then
+    echo "!echo settings from local settings file: $LOCAL_HIVE_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
+    cat "$LOCAL_HIVE_SETTINGS_FILE" >> "$COMBINED_PARAMS_FILE"
+  else
+    echo "!echo no settings from local settings file: $LOCAL_HIVE_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
+  fi
 
-	if [ -n "$USER_QUERY_PARAMS_FILE" ]
-	then
-		if [ -r "$USER_QUERY_PARAMS_FILE" ]
-		then
-			echo "!echo settings file from -y <query parameter file> command line argument: $USER_QUERY_PARAMS_FILE ;" >> "$COMBINED_PARAMS_FILE"
-			cat "$USER_QUERY_PARAMS_FILE" >> "$COMBINED_PARAMS_FILE"
-		else
-			echo "User query parameter file $USER_QUERY_PARAMS_FILE can not be read."
-			rm -rf "$COMBINED_PARAMS_FILE"
-			return 1
-		fi
-	else
-		echo "!echo no settings file from -y <query parameter file> command line argument ;" >> "$COMBINED_PARAMS_FILE"
-	fi
+  if [ -n "$USER_QUERY_PARAMS_FILE" ]
+  then
+    if [ -r "$USER_QUERY_PARAMS_FILE" ]
+    then
+      echo "!echo settings file from -y <query parameter file> command line argument: $USER_QUERY_PARAMS_FILE ;" >> "$COMBINED_PARAMS_FILE"
+      cat "$USER_QUERY_PARAMS_FILE" >> "$COMBINED_PARAMS_FILE"
+    else
+      echo "User query parameter file $USER_QUERY_PARAMS_FILE can not be read."
+      rm -rf "$COMBINED_PARAMS_FILE"
+      return 1
+    fi
+  else
+    echo "!echo no settings file from -y <query parameter file> command line argument ;" >> "$COMBINED_PARAMS_FILE"
+  fi
 
-	if [ -n "$USER_HIVE_SETTINGS_FILE" ]
-	then
-		echo "!echo settings file from -z <hive settings file> command line argument: $USER_HIVE_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
-		if [ -r "$USER_HIVE_SETTINGS_FILE" ]
-		then
-			cat "$GLOBAL_SETTINGS_FILE" >> "$COMBINED_PARAMS_FILE"
-		else
-			echo "User hive settings file $USER_HIVE_SETTINGS_FILE can not be read."
-			rm -rf "$COMBINED_PARAMS_FILE"
-			return 1
-		fi
-	else
-		echo "!echo no settings file from -z <hive settings file> command line argument ;" >> "$COMBINED_PARAMS_FILE"
-	fi
-	return 0
+  if [ -n "$USER_HIVE_SETTINGS_FILE" ]
+  then
+    echo "!echo settings file from -z <hive settings file> command line argument: $USER_HIVE_SETTINGS_FILE ;" >> "$COMBINED_PARAMS_FILE"
+    if [ -r "$USER_HIVE_SETTINGS_FILE" ]
+    then
+      cat "$GLOBAL_SETTINGS_FILE" >> "$COMBINED_PARAMS_FILE"
+    else
+      echo "User hive settings file $USER_HIVE_SETTINGS_FILE can not be read."
+      rm -rf "$COMBINED_PARAMS_FILE"
+      return 1
+    fi
+  else
+    echo "!echo no settings file from -z <hive settings file> command line argument ;" >> "$COMBINED_PARAMS_FILE"
+  fi
+  return 0
 }
 
 initQueryEnv () {
-	if [ -z "$QUERY_NUMBER" ]
-	then
-		echo "The query number must be set."
-		return 1
-	fi
+  if [ -z "$QUERY_NUMBER" ]
+  then
+    echo "The query number must be set."
+    return 1
+  fi
 
-	if [[ $QUERY_NUMBER -lt 1 || $QUERY_NUMBER -gt 30 ]]
-	then
-		echo "Query number must be between 1 and 30"
-		return 1
-	fi
+  if [[ $QUERY_NUMBER -lt 1 || $QUERY_NUMBER -gt 30 ]]
+  then
+    echo "Query number must be between 1 and 30"
+    return 1
+  fi
 
-	if [ $QUERY_NUMBER -lt 10 ]
-	then
-		QUERY_NAME=q0$QUERY_NUMBER
-	else
-		QUERY_NAME=q$QUERY_NUMBER
-	fi
+  if [ $QUERY_NUMBER -lt 10 ]
+  then
+    QUERY_NAME=q0$QUERY_NUMBER
+  else
+    QUERY_NAME=q$QUERY_NUMBER
+  fi
 
-	QUERY_DIR="$BIG_BENCH_QUERIES_DIR/$QUERY_NAME"
-	if [ ! -d "$QUERY_DIR" ]
-	then
-		echo "Query directory $QUERY_DIR does not exist"
-		return 1
-	fi
+  QUERY_DIR="$BIG_BENCH_QUERIES_DIR/$QUERY_NAME"
+  if [ ! -d "$QUERY_DIR" ]
+  then
+    echo "Query directory $QUERY_DIR does not exist"
+    return 1
+  fi
 
-	LOCAL_HIVE_SETTINGS_FILE="$QUERY_DIR/hiveLocalSettings.sql"
-	if ! buildCombinedParamsFile
-	then
-		return 1
-	fi
+  LOCAL_HIVE_SETTINGS_FILE="$QUERY_DIR/hiveLocalSettings.sql"
+  if ! buildCombinedParamsFile
+  then
+    return 1
+  fi
 
-	TABLE_PREFIX="${QUERY_NAME}_${BINARY_TYPE}_${BENCHMARK_PHASE}_${STREAM_NUMBER}"
+  TABLE_PREFIX="${QUERY_NAME}_${BINARY_TYPE}_${BENCHMARK_PHASE}_${STREAM_NUMBER}"
 
-	RESULT_TABLE="${TABLE_PREFIX}_result"
-	RESULT_DIR="$BIG_BENCH_HDFS_ABSOLUTE_QUERY_RESULT_DIR/$RESULT_TABLE"
-	TEMP_TABLE="${TABLE_PREFIX}_temp"
-	TEMP_DIR="$BIG_BENCH_HDFS_ABSOLUTE_TEMP_DIR/$TEMP_TABLE"
+  RESULT_TABLE="${TABLE_PREFIX}_result"
+  RESULT_DIR="$BIG_BENCH_HDFS_ABSOLUTE_QUERY_RESULT_DIR/$RESULT_TABLE"
+  TEMP_TABLE="${TABLE_PREFIX}_temp"
+  TEMP_DIR="$BIG_BENCH_HDFS_ABSOLUTE_TEMP_DIR/$TEMP_TABLE"
 
-	LOG_FILE_NAME="$BIG_BENCH_LOGS_DIR/${TABLE_PREFIX}.log"
+  LOG_FILE_NAME="$BIG_BENCH_LOGS_DIR/${TABLE_PREFIX}.log"
 
-	#echo "set BENCHMARK_PHASE=\"$BENCHMARK_PHASE\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set STREAM_NUMBER=\"$STREAM_NUMBER\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set QUERY_NAME=\"$QUERY_NAME\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set QUERY_DIR=\"$QUERY_DIR\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set RESULT_TABLE=\"$RESULT_TABLE\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set RESULT_DIR=\"$RESULT_DIR\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set TEMP_TABLE=\"$TEMP_TABLE\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set TEMP_DIR=\"$TEMP_DIR\";" >> "$COMBINED_PARAMS_FILE"
-	#echo "set TABLE_PREFIX=\"$TABLE_PREFIX\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set BENCHMARK_PHASE=\"$BENCHMARK_PHASE\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set STREAM_NUMBER=\"$STREAM_NUMBER\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set QUERY_NAME=\"$QUERY_NAME\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set QUERY_DIR=\"$QUERY_DIR\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set RESULT_TABLE=\"$RESULT_TABLE\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set RESULT_DIR=\"$RESULT_DIR\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set TEMP_TABLE=\"$TEMP_TABLE\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set TEMP_DIR=\"$TEMP_DIR\";" >> "$COMBINED_PARAMS_FILE"
+  #echo "set TABLE_PREFIX=\"$TABLE_PREFIX\";" >> "$COMBINED_PARAMS_FILE"
 
-	HIVE_PARAMS="$HIVE_PARAMS -hiveconf BENCHMARK_PHASE=$BENCHMARK_PHASE -hiveconf STREAM_NUMBER=$STREAM_NUMBER -hiveconf QUERY_NAME=$QUERY_NAME -hiveconf QUERY_DIR=$QUERY_DIR -hiveconf RESULT_TABLE=$RESULT_TABLE -hiveconf RESULT_DIR=$RESULT_DIR -hiveconf TEMP_TABLE=$TEMP_TABLE -hiveconf TEMP_DIR=$TEMP_DIR -hiveconf TABLE_PREFIX=$TABLE_PREFIX"
+  HIVE_PARAMS="$HIVE_PARAMS -hiveconf BENCHMARK_PHASE=$BENCHMARK_PHASE -hiveconf STREAM_NUMBER=$STREAM_NUMBER -hiveconf QUERY_NAME=$QUERY_NAME -hiveconf QUERY_DIR=$QUERY_DIR -hiveconf RESULT_TABLE=$RESULT_TABLE -hiveconf RESULT_DIR=$RESULT_DIR -hiveconf TEMP_TABLE=$TEMP_TABLE -hiveconf TEMP_DIR=$TEMP_DIR -hiveconf TABLE_PREFIX=$TABLE_PREFIX"
 
-	# source run.sh as late as possible to allow run.sh to use all above defined variables
-	SCRIPT_FILENAME="$QUERY_DIR/run.sh"
-	if [ -r "$SCRIPT_FILENAME" ]
-	then
-		source "$SCRIPT_FILENAME"
-	else
-		echo "File $SCRIPT_FILENAME containing main method not found, aborting script."
-		return 1
-	fi
+  # source run.sh as late as possible to allow run.sh to use all above defined variables
+  SCRIPT_FILENAME="$QUERY_DIR/run.sh"
+  if [ -r "$SCRIPT_FILENAME" ]
+  then
+    source "$SCRIPT_FILENAME"
+  else
+    echo "File $SCRIPT_FILENAME containing main method not found, aborting script."
+    return 1
+  fi
 
-	# check if the main method was implemented properly in the run.sh
-	QUERY_MAIN_METHOD="query_run_main_method"
-	if ! declare -F "$QUERY_MAIN_METHOD" > /dev/null 2>&1
-	then
-		echo "$QUERY_MAIN_METHOD was not implemented, aborting script"
-		return 1
-	fi
+  # check if the main method was implemented properly in the run.sh
+  QUERY_MAIN_METHOD="query_run_main_method"
+  if ! declare -F "$QUERY_MAIN_METHOD" > /dev/null 2>&1
+  then
+    echo "$QUERY_MAIN_METHOD was not implemented, aborting script"
+    return 1
+  fi
 
-	# check if the clean method was implemented properly in the run.sh
-	QUERY_CLEAN_METHOD="query_run_clean_method"
-	if ! declare -F "$QUERY_CLEAN_METHOD" > /dev/null 2>&1
-	then
-		echo "$QUERY_CLEAN_METHOD was not implemented, aborting script"
-		return 1
-	fi
-	return 0
+  # check if the clean method was implemented properly in the run.sh
+  QUERY_CLEAN_METHOD="query_run_clean_method"
+  if ! declare -F "$QUERY_CLEAN_METHOD" > /dev/null 2>&1
+  then
+    echo "$QUERY_CLEAN_METHOD was not implemented, aborting script"
+    return 1
+  fi
+  return 0
 }
 
 # parse command line arguments
 while getopts ":b:d:f:hm:p:q:s:t:v:w:y:z:" OPT; do
-	case "$OPT" in
-		b)
-			USER_BINARY_TYPE="$OPTARG"
-		;;
-		d)
-			#echo "-d was triggered, Parameter: $OPTARG" >&2
-			DEBUG_QUERY_PART="$OPTARG"
-		;;
-		f)
-			#echo "-f was triggered, Parameter: $OPTARG" >&2
-			SCALE_FACTOR="$OPTARG"
-		;;
-		h)
-			#echo "-h was triggered, Parameter: $OPTARG" >&2
-			SHOW_HELP="true"
-		;;
-		m)
-			#echo "-m was triggered, Parameter: $OPTARG" >&2
-			MAP_TASKS="$OPTARG"
-		;;
-		p)
-			#echo "-p was triggered, Parameter: $OPTARG" >&2
-			USER_BENCHMARK_PHASE="$OPTARG"
-		;;
-		q)
-			#echo "-q was triggered, Parameter: $OPTARG" >&2
-			QUERY_NUMBER="$OPTARG"
-		;;
-		s)
-			#echo "-t was triggered, Parameter: $OPTARG" >&2
-			USER_NUMBER_OF_PARALLEL_STREAMS="$OPTARG"
-		;;
-		t)
-			#echo "-s was triggered, Parameter: $OPTARG" >&2
-			USER_STREAM_NUMBER="$OPTARG"
-		;;
-		v)
-			#echo "-v was triggered, Parameter: $OPTARG" >&2
-			USER_POPULATE_FILE="$OPTARG"
-		;;
-		w)
-			#echo "-w was triggered, Parameter: $OPTARG" >&2
-			USER_REFRESH_FILE="$OPTARG"
-		;;
-		y)
-			#echo "-y was triggered, Parameter: $OPTARG" >&2
-			USER_QUERY_PARAMS_FILE="$OPTARG"
-		;;
-		z)
-			#echo "-z was triggered, Parameter: $OPTARG" >&2
-			USER_HIVE_SETTINGS_FILE="$OPTARG"
-		;;
-		\?)
-			echo "Invalid option: -$OPTARG" >&2
-			exit 1
-		;;
-		:)
-			echo "Option -$OPTARG requires an argument." >&2
-			exit 1
-	;;
-	esac
-	LIST_OF_USER_OPTIONS="$LIST_OF_USER_OPTIONS -$OPT $OPTARG"
+  case "$OPT" in
+    b)
+      USER_BINARY_TYPE="$OPTARG"
+    ;;
+    d)
+      #echo "-d was triggered, Parameter: $OPTARG" >&2
+      DEBUG_QUERY_PART="$OPTARG"
+    ;;
+    f)
+      #echo "-f was triggered, Parameter: $OPTARG" >&2
+      SCALE_FACTOR="$OPTARG"
+    ;;
+    h)
+      #echo "-h was triggered, Parameter: $OPTARG" >&2
+      SHOW_HELP="true"
+    ;;
+    m)
+      #echo "-m was triggered, Parameter: $OPTARG" >&2
+      MAP_TASKS="$OPTARG"
+    ;;
+    p)
+      #echo "-p was triggered, Parameter: $OPTARG" >&2
+      USER_BENCHMARK_PHASE="$OPTARG"
+    ;;
+    q)
+      #echo "-q was triggered, Parameter: $OPTARG" >&2
+      QUERY_NUMBER="$OPTARG"
+    ;;
+    s)
+      #echo "-t was triggered, Parameter: $OPTARG" >&2
+      USER_NUMBER_OF_PARALLEL_STREAMS="$OPTARG"
+    ;;
+    t)
+      #echo "-s was triggered, Parameter: $OPTARG" >&2
+      USER_STREAM_NUMBER="$OPTARG"
+    ;;
+    v)
+      #echo "-v was triggered, Parameter: $OPTARG" >&2
+      USER_POPULATE_FILE="$OPTARG"
+    ;;
+    w)
+      #echo "-w was triggered, Parameter: $OPTARG" >&2
+      USER_REFRESH_FILE="$OPTARG"
+    ;;
+    y)
+      #echo "-y was triggered, Parameter: $OPTARG" >&2
+      USER_QUERY_PARAMS_FILE="$OPTARG"
+    ;;
+    z)
+      #echo "-z was triggered, Parameter: $OPTARG" >&2
+      USER_HIVE_SETTINGS_FILE="$OPTARG"
+    ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+    ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+  ;;
+  esac
+  LIST_OF_USER_OPTIONS="$LIST_OF_USER_OPTIONS -$OPT $OPTARG"
 done
 
 MODULES_DIR="$BIG_BENCH_BASH_SCRIPT_DIR/modules"
@@ -236,29 +236,29 @@ MODULES_DIR="$BIG_BENCH_BASH_SCRIPT_DIR/modules"
 # show help if no arguments or '-h' present
 if [[ $# -eq 0 || "$SHOW_HELP" = "true" ]]
 then
-	echo "Usage: `basename $0` [global options] module [module options]"
-	echo
-	echo "Global options are:"
-	echo -e "-b\tbinary to use (hive/shark)"
-	echo -e "-d\tquery part to debug"
-	echo -e "-f\tscale factor for PDGF"
-	echo -e "-h\tshow this help"
-	echo -e "-m\tmap tasks for PDGF"
-	echo -e "-p\tbenchmark phase to use"
-	echo -e "-q\tquery number to run"
-	echo -e "-s\tnumber of parallel streams (only used when supported by module)"
-	echo -e "-t\tstream number for query run"
-	echo -e "-v\tsql script for metastore population"
-	echo -e "-w\tsql script for metastore refresh"
-	echo -e "-y\tfile with user defined query parameters"
-	echo -e "-z\tfile with user defined hive settings"
-	echo
-	echo "Module options are specific to the used module and are therefore implemented there"
-	echo
-	echo "List of available modules:"
-	ls -1 "$MODULES_DIR"
-	#find "$MODULES_DIR" -type f -exec basename {} \;
-	exit 0
+  echo "Usage: `basename $0` [global options] module [module options]"
+  echo
+  echo "Global options are:"
+  echo -e "-b\tbinary to use (hive/shark)"
+  echo -e "-d\tquery part to debug"
+  echo -e "-f\tscale factor for PDGF"
+  echo -e "-h\tshow this help"
+  echo -e "-m\tmap tasks for PDGF"
+  echo -e "-p\tbenchmark phase to use"
+  echo -e "-q\tquery number to run"
+  echo -e "-s\tnumber of parallel streams (only used when supported by module)"
+  echo -e "-t\tstream number for query run"
+  echo -e "-v\tsql script for metastore population"
+  echo -e "-w\tsql script for metastore refresh"
+  echo -e "-y\tfile with user defined query parameters"
+  echo -e "-z\tfile with user defined hive settings"
+  echo
+  echo "Module options are specific to the used module and are therefore implemented there"
+  echo
+  echo "List of available modules:"
+  ls -1 "$MODULES_DIR"
+  #find "$MODULES_DIR" -type f -exec basename {} \;
+  exit 0
 fi
 
 # remove options from parameter list
@@ -275,55 +275,55 @@ GLOBAL_NUMBER_OF_PARALLEL_STREAMS="1"
 
 # set the binary to use according to the user input
 case "$USER_BINARY_TYPE" in
-	"hive")
-		BINARY="$HIVE_BINARY"
-	;;
-	"shark")
-		BINARY="$SHARK_BINARY"
-	;;
-	"")
-		BINARY="$DEFAULT_BINARY"
-	;;
+  "hive")
+    BINARY="$HIVE_BINARY"
+  ;;
+  "shark")
+    BINARY="$SHARK_BINARY"
+  ;;
+  "")
+    BINARY="$DEFAULT_BINARY"
+  ;;
 esac
 
 # set other variables for the chosen binary
 case "$BINARY" in
-	"$HIVE_BINARY")
-		BINARY_TYPE="hive"
-		GLOBAL_SETTINGS_FILE="$BIG_BENCH_HIVE_SCRIPT_DIR/hiveSettings.sql"
-		GLOBAL_POPULATE_FILE="${USER_POPULATE_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveCreateLoad.sql"}"
-		GLOBAL_REFRESH_FILE="${USER_REFRESH_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveRefreshCreateLoad.sql"}"
-	;;
-	"$SHARK_BINARY")
-		BINARY_TYPE="shark"
-		GLOBAL_SETTINGS_FILE="$BIG_BENCH_HIVE_SCRIPT_DIR/sharkSettings.sql"
-		GLOBAL_POPULATE_FILE="${USER_POPULATE_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveCreateLoad.sql"}"
-		GLOBAL_REFRESH_FILE="${USER_REFRESH_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveRefreshCreateLoad.sql"}"
-	;;
+  "$HIVE_BINARY")
+    BINARY_TYPE="hive"
+    GLOBAL_SETTINGS_FILE="$BIG_BENCH_HIVE_SCRIPT_DIR/hiveSettings.sql"
+    GLOBAL_POPULATE_FILE="${USER_POPULATE_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveCreateLoad.sql"}"
+    GLOBAL_REFRESH_FILE="${USER_REFRESH_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveRefreshCreateLoad.sql"}"
+  ;;
+  "$SHARK_BINARY")
+    BINARY_TYPE="shark"
+    GLOBAL_SETTINGS_FILE="$BIG_BENCH_HIVE_SCRIPT_DIR/sharkSettings.sql"
+    GLOBAL_POPULATE_FILE="${USER_POPULATE_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveCreateLoad.sql"}"
+    GLOBAL_REFRESH_FILE="${USER_REFRESH_FILE:-"$BIG_BENCH_HIVE_SCRIPT_DIR/hiveRefreshCreateLoad.sql"}"
+  ;;
 esac
 
 if [ ! -f "$GLOBAL_QUERY_PARAMS_FILE" ]
 then
-	echo "Global query parameter file $GLOBAL_QUERY_PARAMS_FILE can not be found"
-	exit 1
+  echo "Global query parameter file $GLOBAL_QUERY_PARAMS_FILE can not be found"
+  exit 1
 fi
 
 if [ ! -f "$GLOBAL_SETTINGS_FILE" ]
 then
-	echo "Global settings file $GLOBAL_SETTINGS_FILE can not be found"
-	exit 1
+  echo "Global settings file $GLOBAL_SETTINGS_FILE can not be found"
+  exit 1
 fi
 
 if [ ! -f "$GLOBAL_POPULATE_FILE" ]
 then
-	echo "Global populate metastore file $GLOBAL_POPULATE_FILE can not be found"
-	exit 1
+  echo "Global populate metastore file $GLOBAL_POPULATE_FILE can not be found"
+  exit 1
 fi
 
 if [ ! -f "$GLOBAL_REFRESH_FILE" ]
 then
-	echo "Global refresh metastore file $GLOBAL_REFRESH_FILE can not be found"
-	exit 1
+  echo "Global refresh metastore file $GLOBAL_REFRESH_FILE can not be found"
+  exit 1
 fi
 
 BENCHMARK_PHASE="${USER_BENCHMARK_PHASE:-$GLOBAL_BENCHMARK_PHASE}"
@@ -333,25 +333,25 @@ NUMBER_OF_PARALLEL_STREAMS="${USER_NUMBER_OF_PARALLEL_STREAMS:-$GLOBAL_NUMBER_OF
 MODULE="$MODULES_DIR/$MODULE_NAME"
 if [ -f "$MODULE" ]
 then
-	source "$MODULE"
+  source "$MODULE"
 else
-	echo "Module $MODULE not found, aborting script."
-	exit 1
+  echo "Module $MODULE not found, aborting script."
+  exit 1
 fi
 
 # check if the run method was implemented properly
 RUN_METHOD="exec$MODULE_NAME"
 if ! declare -F "$RUN_METHOD" > /dev/null 2>&1
 then
-	echo "$RUN_METHOD was not implemented, aborting script"
-	exit 1
+  echo "$RUN_METHOD was not implemented, aborting script"
+  exit 1
 fi
 
 COMBINED_PARAMS_FILE="`mktemp`"
 if buildCombinedParamsFile
 then
-	# run module
-	"$RUN_METHOD" "$@"
+  # run module
+  "$RUN_METHOD" "$@"
 fi
 
 rm -rf "$COMBINED_PARAMS_FILE"
diff --git a/scripts/modules/hadoopDataGen b/scripts/modules/hadoopDataGen
--- a/scripts/modules/hadoopDataGen
+++ b/scripts/modules/hadoopDataGen
@@ -1,143 +1,143 @@
 #!/usr/bin/env bash
 
 exechadoopDataGen () {
-	# extract options and their arguments into variables.
-	#echo "USAGE: -mapTasks <number> -sf <number>  (SF: scalingFactor 1==1GB, 10==10GB, .. , 1000=1TB, etc. Location of generated data can be set in /setEnvVars configuration file  with the BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR property)"
+  # extract options and their arguments into variables.
+  #echo "USAGE: -mapTasks <number> -sf <number>  (SF: scalingFactor 1==1GB, 10==10GB, .. , 1000=1TB, etc. Location of generated data can be set in /setEnvVars configuration file  with the BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR property)"
 
-	if [ -z "$MAP_TASKS" ]
-	then
-		echo "The number of map tasks is a required option"
-		return 1
-	fi
+  if [ -z "$MAP_TASKS" ]
+  then
+    echo "The number of map tasks is a required option"
+    return 1
+  fi
 
-	local HadoopClusterExecOptions="-mapTasks $MAP_TASKS"
+  local HadoopClusterExecOptions="-mapTasks $MAP_TASKS"
 
-	if [ -n "$SCALE_FACTOR" ]
-	then
-		local PDGF_OPTIONS="-sf $SCALE_FACTOR"
-	fi
+  if [ -n "$SCALE_FACTOR" ]
+  then
+    local PDGF_OPTIONS="-sf $SCALE_FACTOR"
+  fi
 
-	echo "PDGFOptions: $PDGF_OPTIONS $@"
-	echo "HadoopClusterExecOptions: $HadoopClusterExecOptions"
+  echo "PDGFOptions: $PDGF_OPTIONS $@"
+  echo "HadoopClusterExecOptions: $HadoopClusterExecOptions"
 
-	local PDGF_ARCHIVE_NAME="pdgfEnvironment.tar"
-	local PDGF_DISTRIBUTED_NODE_DIR="$PDGF_ARCHIVE_NAME/data-generator/"
-	local PDGF_ARCHIVE_PATH="$BIG_BENCH_HOME/$PDGF_ARCHIVE_NAME"
+  local PDGF_ARCHIVE_NAME="pdgfEnvironment.tar"
+  local PDGF_DISTRIBUTED_NODE_DIR="$PDGF_ARCHIVE_NAME/data-generator/"
+  local PDGF_ARCHIVE_PATH="$BIG_BENCH_HOME/$PDGF_ARCHIVE_NAME"
 
-	if grep -q "IS_EULA_ACCEPTED=true" "$BIG_BENCH_DATA_GENERATOR_DIR/Constants.properties"; then
-		echo "EULA is accepted"
-	else
-		echo "==============================================="
-		echo "data generator EULA"
-		echo "==============================================="
-		echo "This is your first run of the data generation tool. Please accept the EULA."
-		java -jar "$BIG_BENCH_DATA_GENERATOR_DIR/pdgf.jar" -ns -c
-		if grep -q "IS_EULA_ACCEPTED=true" "$BIG_BENCH_DATA_GENERATOR_DIR/Constants.properties"; then
-			echo "OK"
-		else
-			echo "ERROR! data generation tool EULA is not accepted. Cannot procced"
-			return 1 
-		fi
-	fi
+  if grep -q "IS_EULA_ACCEPTED=true" "$BIG_BENCH_DATA_GENERATOR_DIR/Constants.properties"; then
+    echo "EULA is accepted"
+  else
+    echo "==============================================="
+    echo "data generator EULA"
+    echo "==============================================="
+    echo "This is your first run of the data generation tool. Please accept the EULA."
+    java -jar "$BIG_BENCH_DATA_GENERATOR_DIR/pdgf.jar" -ns -c
+    if grep -q "IS_EULA_ACCEPTED=true" "$BIG_BENCH_DATA_GENERATOR_DIR/Constants.properties"; then
+      echo "OK"
+    else
+      echo "ERROR! data generation tool EULA is not accepted. Cannot procced"
+      return 1 
+    fi
+  fi
 
-	# delete any previously generated data
-	echo "==============================================="
-	echo "Deleting any previously generated data."
-	echo "==============================================="
-	"${BIG_BENCH_BASH_SCRIPT_DIR}/bigBench" $LIST_OF_USER_OPTIONS cleanData
-	echo "OK"
-	echo "==============================================="
-	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}
-	echo "==============================================="
-	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
-	rc=$?
-	if [[ $rc != 0 ]] ; then
-		echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
-		return $rc
-	fi
+  # delete any previously generated data
+  echo "==============================================="
+  echo "Deleting any previously generated data."
+  echo "==============================================="
+  "${BIG_BENCH_BASH_SCRIPT_DIR}/bigBench" $LIST_OF_USER_OPTIONS cleanData
+  echo "OK"
+  echo "==============================================="
+  echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}
+  echo "==============================================="
+  hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+  rc=$?
+  if [[ $rc != 0 ]] ; then
+    echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+    return $rc
+  fi
 
-	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
-	rc=$?
-	if [[ $rc != 0 ]] ; then
-		echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
-		return $rc
-	fi
+  hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+  rc=$?
+  if [[ $rc != 0 ]] ; then
+    echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+    return $rc
+  fi
 
-	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+  hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
 
-	echo "OK"
-	echo "==============================================="
-	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}
-	echo "==============================================="
-	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
-	rc=$?
-	if [[ $rc != 0 ]] ; then
-		echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
-		return $rc
-	fi
+  echo "OK"
+  echo "==============================================="
+  echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}
+  echo "==============================================="
+  hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+  rc=$?
+  if [[ $rc != 0 ]] ; then
+    echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+    return $rc
+  fi
 
-	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
-	rc=$?
-	if [[ $rc != 0 ]] ; then
-		echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
-		return $rc
-	fi
+  hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+  rc=$?
+  if [[ $rc != 0 ]] ; then
+    echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+    return $rc
+  fi
 
-	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
-	echo "OK"
+  hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+  echo "OK"
 
 
-	echo "==============================================="
-	echo "Creating data generator archive to upload to DistCache"
-	echo "==============================================="
-	rm -f "$PDGF_ARCHIVE_PATH"
-	tar -C "$BIG_BENCH_HOME" -caf "$PDGF_ARCHIVE_PATH" data-generator/
-	rc=$?
-	if [[ $rc != 0 ]] ; then
-		echo "Creating data generator archive failed"
-		return $rc
-	fi
-	echo "OK"
+  echo "==============================================="
+  echo "Creating data generator archive to upload to DistCache"
+  echo "==============================================="
+  rm -f "$PDGF_ARCHIVE_PATH"
+  tar -C "$BIG_BENCH_HOME" -caf "$PDGF_ARCHIVE_PATH" data-generator/
+  rc=$?
+  if [[ $rc != 0 ]] ; then
+    echo "Creating data generator archive failed"
+    return $rc
+  fi
+  echo "OK"
 
-	echo "==============================================="
-	echo "Starting distributed hadoop data generation job with: $HadoopClusterExecOptions"
-	echo "Temporary result data in hdfs: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR} (you can change the data generation target folder in  the /setEnvVars configuration file with the BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR property)"
-	echo "logs: ${BIG_BENCH_DATAGEN_STAGE_LOG}"
-	echo "==============================================="
-	local HADOOP_CP=`hadoop classpath`
-	echo "HADOOP CLASSPATH: "$HADOOP_CP
+  echo "==============================================="
+  echo "Starting distributed hadoop data generation job with: $HadoopClusterExecOptions"
+  echo "Temporary result data in hdfs: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR} (you can change the data generation target folder in  the /setEnvVars configuration file with the BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR property)"
+  echo "logs: ${BIG_BENCH_DATAGEN_STAGE_LOG}"
+  echo "==============================================="
+  local HADOOP_CP=`hadoop classpath`
+  echo "HADOOP CLASSPATH: "$HADOOP_CP
 
-	local PDGF_CLUSTER_CONF="-Dpdgf.log.folder=/tmp/pdgfLog/HadoopClusterExec.taskNumber -Dcore-site.xml=${BIG_BENCH_DATAGEN_CORE_SITE} -Dhdfs-site.xml=${BIG_BENCH_DATAGEN_HDFS_SITE} -Djava.library.path=${BIG_BENCH_HADOOP_LIBS_NATIVE} -DFileChannelProvider=pdgf.util.caching.fileWriter.HDFSChannelProvider -Ddfs.replication.override=${BIG_BENCH_DATAGEN_DFS_REPLICATION} "
-	echo "PDGF_CLUSTER_CONF: $PDGF_CLUSTER_CONF"
+  local PDGF_CLUSTER_CONF="-Dpdgf.log.folder=/tmp/pdgfLog/HadoopClusterExec.taskNumber -Dcore-site.xml=${BIG_BENCH_DATAGEN_CORE_SITE} -Dhdfs-site.xml=${BIG_BENCH_DATAGEN_HDFS_SITE} -Djava.library.path=${BIG_BENCH_HADOOP_LIBS_NATIVE} -DFileChannelProvider=pdgf.util.caching.fileWriter.HDFSChannelProvider -Ddfs.replication.override=${BIG_BENCH_DATAGEN_DFS_REPLICATION} "
+  echo "PDGF_CLUSTER_CONF: $PDGF_CLUSTER_CONF"
 
-	echo "create $BIG_BENCH_LOGS_DIR folder"
-	mkdir -p "$BIG_BENCH_LOGS_DIR"
+  echo "create $BIG_BENCH_LOGS_DIR folder"
+  mkdir -p "$BIG_BENCH_LOGS_DIR"
 
-	echo hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 0 -o "'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
+  echo hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 0 -o "'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
 
-	time (hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 0 -o "'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" ; echo  "======= Generating data time =========") > >(tee -a "$BIG_BENCH_DATAGEN_STAGE_LOG") 2>&1
-	rc=$?
-	if [[ $rc != 0 ]] ; then
-		echo "Error executing data generation job"
-		return $rc
-	fi
+  time (hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 0 -o "'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" ; echo  "======= Generating data time =========") > >(tee -a "$BIG_BENCH_DATAGEN_STAGE_LOG") 2>&1
+  rc=$?
+  if [[ $rc != 0 ]] ; then
+    echo "Error executing data generation job"
+    return $rc
+  fi
 
-	echo hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 1 -o "'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
+  echo hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 1 -o "'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
 
-	time (hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 1 -o "'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" ; echo  "======= Generating data time =========") > >(tee -a "$BIG_BENCH_DATAGEN_STAGE_LOG") 2>&1
-	rc=$?
-	if [[ $rc != 0 ]] ; then
-		echo "Error executing refresh data generation job"
-		return $rc
-	fi
+  time (hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 1 -o "'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" ; echo  "======= Generating data time =========") > >(tee -a "$BIG_BENCH_DATAGEN_STAGE_LOG") 2>&1
+  rc=$?
+  if [[ $rc != 0 ]] ; then
+    echo "Error executing refresh data generation job"
+    return $rc
+  fi
 
-	##cleanup
-	rm -f ${PDGF_ARCHIVE_PATH}
+  ##cleanup
+  rm -f ${PDGF_ARCHIVE_PATH}
 
-	echo "==============================================="
-	echo "Hadoop data generation job finished. "
-	echo "logs: ${BIG_BENCH_DATAGEN_STAGE_LOG}"
-	echo "View generated files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
-	echo "View generated refresh files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
-	echo "==============================================="
+  echo "==============================================="
+  echo "Hadoop data generation job finished. "
+  echo "logs: ${BIG_BENCH_DATAGEN_STAGE_LOG}"
+  echo "View generated files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+  echo "View generated refresh files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+  echo "==============================================="
 }
diff --git a/scripts/modules/runQuery b/scripts/modules/runQuery
--- a/scripts/modules/runQuery
+++ b/scripts/modules/runQuery
@@ -1,62 +1,62 @@
 #!/usr/bin/env bash
 
 execrunQuery () {
-	if ! initQueryEnv
-	then
-		return 1
-	fi
+  if ! initQueryEnv
+  then
+    return 1
+  fi
 
-	echo "==============================================="
-	echo "Running query  : $QUERY_NAME"
-	echo "-----------------------------------------------"
-	echo "used binary: $BINARY"
-	echo "benchmark phase: $BENCHMARK_PHASE"
-	echo "stream number  : $STREAM_NUMBER"
-	echo "user parameter file : $USER_QUERY_PARAMS_FILE"
-	echo "user settings file  :$USER_HIVE_SETTINGS_FILE"
-	if [[ -n "$DEBUG_QUERY_PART" ]]; then
-		echo "query part to debug: $DEBUG_QUERY_PART"
-	fi
-	echo "log: $LOG_FILE_NAME"
-	echo "==============================================="	
+  echo "==============================================="
+  echo "Running query  : $QUERY_NAME"
+  echo "-----------------------------------------------"
+  echo "used binary: $BINARY"
+  echo "benchmark phase: $BENCHMARK_PHASE"
+  echo "stream number  : $STREAM_NUMBER"
+  echo "user parameter file : $USER_QUERY_PARAMS_FILE"
+  echo "user settings file  :$USER_HIVE_SETTINGS_FILE"
+  if [[ -n "$DEBUG_QUERY_PART" ]]; then
+    echo "query part to debug: $DEBUG_QUERY_PART"
+  fi
+  echo "log: $LOG_FILE_NAME"
+  echo "==============================================="  
 
-	### Checking required folder: logs/; tmp/; result/ if they exist, create them and set permissions
+  ### Checking required folder: logs/; tmp/; result/ if they exist, create them and set permissions
 
-	echo "checking existence of local: $BIG_BENCH_LOGS_DIR"
-	if [ ! -d "$BIG_BENCH_LOGS_DIR" ]; then
-		mkdir -p "$BIG_BENCH_LOGS_DIR"
-	fi
+  echo "checking existence of local: $BIG_BENCH_LOGS_DIR"
+  if [ ! -d "$BIG_BENCH_LOGS_DIR" ]; then
+    mkdir -p "$BIG_BENCH_LOGS_DIR"
+  fi
 
-	if [ ! -e "$LOG_FILE_NAME" ] ; then
-    	touch "$LOG_FILE_NAME"
-	fi
+  if [ ! -e "$LOG_FILE_NAME" ] ; then
+      touch "$LOG_FILE_NAME"
+  fi
 
-	if [ ! -w "$LOG_FILE_NAME" ] ; then
-    	echo "ERROR: cannot write to: $LOG_FILE_NAME, no permission"
-    	return 1
-	fi
+  if [ ! -w "$LOG_FILE_NAME" ] ; then
+      echo "ERROR: cannot write to: $LOG_FILE_NAME, no permission"
+      return 1
+  fi
 
-	echo "creating folders and setting permissions"
-	hadoop fs -rm -r -skipTrash "${RESULT_DIR}" &
-	hadoop fs -rm -r -skipTrash "${TEMP_DIR}" &
-	wait
-	hadoop fs -mkdir -p "${RESULT_DIR}" &
-	hadoop fs -mkdir -p "${TEMP_DIR}" &
-	wait
-	hadoop fs -chmod uga+rw "${BIG_BENCH_HDFS_ABSOLUTE_TEMP_DIR}" &
-	hadoop fs -chmod uga+rw "${BIG_BENCH_HDFS_ABSOLUTE_QUERY_RESULT_DIR}" &
-	hadoop fs -chmod uga+rw "${RESULT_DIR}" &
-	hadoop fs -chmod uga+rw "${TEMP_DIR}" &
-	wait
+  echo "creating folders and setting permissions"
+  hadoop fs -rm -r -skipTrash "${RESULT_DIR}" &
+  hadoop fs -rm -r -skipTrash "${TEMP_DIR}" &
+  wait
+  hadoop fs -mkdir -p "${RESULT_DIR}" &
+  hadoop fs -mkdir -p "${TEMP_DIR}" &
+  wait
+  hadoop fs -chmod uga+rw "${BIG_BENCH_HDFS_ABSOLUTE_TEMP_DIR}" &
+  hadoop fs -chmod uga+rw "${BIG_BENCH_HDFS_ABSOLUTE_QUERY_RESULT_DIR}" &
+  hadoop fs -chmod uga+rw "${RESULT_DIR}" &
+  hadoop fs -chmod uga+rw "${TEMP_DIR}" &
+  wait
 
-	# start timed execution of query. Stderr is appended to stdout and both are written into logs/q??.log and to console
+  # start timed execution of query. Stderr is appended to stdout and both are written into logs/q??.log and to console
 
-	# Run the main method implemented in the query's run.sh
-	time ("$QUERY_MAIN_METHOD" ; echo "======= $TABLE_PREFIX time =========") > >(tee -a "$LOG_FILE_NAME") 2>&1 
-	echo "==========================="
+  # Run the main method implemented in the query's run.sh
+  time ("$QUERY_MAIN_METHOD" ; echo "======= $TABLE_PREFIX time =========") > >(tee -a "$LOG_FILE_NAME") 2>&1 
+  echo "==========================="
 
-	echo "======= $TABLE_PREFIX result =======" | tee -a "$LOG_FILE_NAME" 2>&1
-	echo "results in: $RESULT_DIR" | tee -a "$LOG_FILE_NAME" 2>&1
-	echo "to display: hadoop fs -cat $RESULT_DIR/*" | tee -a "$LOG_FILE_NAME" 2>&1
-	echo "=========================" | tee -a "$LOG_FILE_NAME" 2>&1
+  echo "======= $TABLE_PREFIX result =======" | tee -a "$LOG_FILE_NAME" 2>&1
+  echo "results in: $RESULT_DIR" | tee -a "$LOG_FILE_NAME" 2>&1
+  echo "to display: hadoop fs -cat $RESULT_DIR/*" | tee -a "$LOG_FILE_NAME" 2>&1
+  echo "=========================" | tee -a "$LOG_FILE_NAME" 2>&1
 }
