initial support for refresh

diff --git a/scripts/modules/clusterDataGen b/scripts/modules/clusterDataGen
--- a/scripts/modules/clusterDataGen
+++ b/scripts/modules/clusterDataGen
@@ -34,23 +34,43 @@ execclusterDataGen () {
 	"${BIG_BENCH_BASH_SCRIPT_DIR}/bigBench" cleanData
 	echo "OK"
 	echo "==============================================="
-	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}
+	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}
 	echo "==============================================="
-	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
 	rc=$?
 	if [[ $rc != 0 ]] ; then
-    	echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
-    	return $rc
+    		echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+    		return $rc
 	fi
 
-	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
 	rc=$?
 	if [[ $rc != 0 ]] ; then
-    	echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
-    	return $rc
+    		echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+    		return $rc
 	fi
 
-	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+
+	echo "OK"
+	echo "==============================================="
+	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}
+	echo "==============================================="
+	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+	rc=$?
+	if [[ $rc != 0 ]] ; then
+    		echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+    		return $rc
+	fi
+
+	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+	rc=$?
+	if [[ $rc != 0 ]] ; then
+    		echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+    		return $rc
+	fi
+
+	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
 	echo "OK"
 
 	echo "==============================================="
@@ -61,12 +81,15 @@ execclusterDataGen () {
 
 	for (( i = 0; i < ${NODE_COUNT}; i++ ));
 	do
-		echo ssh ${BIG_BENCH_SSH_OPTIONS} ${IPs[$i]} java ${BIG_BENCH_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:${BIG_BENCH_DATA_GENERATOR_DIR}/pdgf.jar" ${CLUSTER_CONF} pdgf.Controller  -nc ${NODE_COUNT} -nn $((i+1)) -ns -c -o "'${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}/'+table.getName()+'/'" -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
-		ssh ${BIG_BENCH_SSH_OPTIONS} ${IPs[$i]} java ${BIG_BENCH_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:${BIG_BENCH_DATA_GENERATOR_DIR}/pdgf.jar" ${CLUSTER_CONF} pdgf.Controller  -nc ${NODE_COUNT} -nn $((i+1)) -ns -c -o "\'${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}/\'+table.getName\(\)+\'/\'" -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" &
+		echo ssh ${BIG_BENCH_SSH_OPTIONS} ${IPs[$i]} java ${BIG_BENCH_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:${BIG_BENCH_DATA_GENERATOR_DIR}/pdgf.jar" ${CLUSTER_CONF} pdgf.Controller -nc ${NODE_COUNT} -nn $((i+1)) -ns -c -sp REFRESH_PHASE 0 -o "'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/'+table.getName()+'/'" -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
+		ssh ${BIG_BENCH_SSH_OPTIONS} ${IPs[$i]} java ${BIG_BENCH_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:${BIG_BENCH_DATA_GENERATOR_DIR}/pdgf.jar" ${CLUSTER_CONF} pdgf.Controller -nc ${NODE_COUNT} -nn $((i+1)) -ns -c -sp REFRESH_PHASE 0 -o "\'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/\'+table.getName\(\)+\'/\'" -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" &
+		echo ssh ${BIG_BENCH_SSH_OPTIONS} ${IPs[$i]} java ${BIG_BENCH_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:${BIG_BENCH_DATA_GENERATOR_DIR}/pdgf.jar" ${CLUSTER_CONF} pdgf.Controller -nc ${NODE_COUNT} -nn $((i+1)) -ns -c -sp REFRESH_PHASE 1 -o "'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/'+table.getName()+'/'" -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
+		ssh ${BIG_BENCH_SSH_OPTIONS} ${IPs[$i]} java ${BIG_BENCH_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:${BIG_BENCH_DATA_GENERATOR_DIR}/pdgf.jar" ${CLUSTER_CONF} pdgf.Controller -nc ${NODE_COUNT} -nn $((i+1)) -ns -c -sp REFRESH_PHASE 1 -o "\'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/\'+table.getName\(\)+\'/\'" -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" &
 	done
 	wait
 	echo "==============================================="
 	echo "SSH cluster data generation job finished. "
-	echo "View generated files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	echo "View generated initial files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+	echo "View generated refresh files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
 	echo "==============================================="
 }
diff --git a/scripts/modules/hadoopDataGen b/scripts/modules/hadoopDataGen
--- a/scripts/modules/hadoopDataGen
+++ b/scripts/modules/hadoopDataGen
@@ -2,7 +2,7 @@
 
 exechadoopDataGen () {
 	# extract options and their arguments into variables.
-	#echo "USAGE: -mapTasks <number> -sf <number>  (SF: scalingFactor 1==1GB, 10==10GB, .. , 1000=1TB, etc. Location of generated data can be set in /setEnvVars configuration file  with the BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR property)"
+	#echo "USAGE: -mapTasks <number> -sf <number>  (SF: scalingFactor 1==1GB, 10==10GB, .. , 1000=1TB, etc. Location of generated data can be set in /setEnvVars configuration file  with the BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR property)"
 
 	if [ -z "$MAP_TASKS" ]
 	then
@@ -47,24 +47,45 @@ exechadoopDataGen () {
 	"${BIG_BENCH_BASH_SCRIPT_DIR}/bigBench" cleanData
 	echo "OK"
 	echo "==============================================="
-	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}
+	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}
 	echo "==============================================="
-	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
 	rc=$?
 	if [[ $rc != 0 ]] ; then
-		echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+		echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
 		return $rc
 	fi
 
-	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
 	rc=$?
 	if [[ $rc != 0 ]] ; then
-		echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+		echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
 		return $rc
 	fi
 
-	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+
 	echo "OK"
+	echo "==============================================="
+	echo "make hdfs benchmark data dir: "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}
+	echo "==============================================="
+	hadoop fs -mkdir -p "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+	rc=$?
+	if [[ $rc != 0 ]] ; then
+		echo "Error creating hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+		return $rc
+	fi
+
+	hadoop fs -chmod -R 777 "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+	rc=$?
+	if [[ $rc != 0 ]] ; then
+		echo "Error setting permission for hdfs dir: ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+		return $rc
+	fi
+
+	hadoop fs -ls "${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
+	echo "OK"
+
 
 	echo "==============================================="
 	echo "Creating data generator archive to upload to DistCache"
@@ -80,7 +101,7 @@ exechadoopDataGen () {
 
 	echo "==============================================="
 	echo "Starting distributed hadoop data generation job with: $HadoopClusterExecOptions"
-	echo "Temporary result data in hdfs: ${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR} (you can change the data generation target folder in  the /setEnvVars configuration file with the BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR property)"
+	echo "Temporary result data in hdfs: ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR} (you can change the data generation target folder in  the /setEnvVars configuration file with the BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR property)"
 	echo "logs: ${BIG_BENCH_DATAGEN_STAGE_LOG}"
 	echo "==============================================="
 	local HADOOP_CP=`hadoop classpath`
@@ -92,12 +113,21 @@ exechadoopDataGen () {
 	echo "create $BIG_BENCH_LOGS_DIR folder"
 	mkdir -p "$BIG_BENCH_LOGS_DIR"
 
-	echo hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives  "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec java ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks  -nn HadoopClusterExec.taskNumber -ns -c -o "'${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
+	echo hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec java ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 0 -o "'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
 
-	time (hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives  "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec java ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks  -nn HadoopClusterExec.taskNumber -ns -c -o "'${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" ; echo  "======= Generating data time =========") > >(tee -a "$BIG_BENCH_DATAGEN_STAGE_LOG") 2>&1
+	time (hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec java ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 0 -o "'${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" ; echo  "======= Generating data time =========") > >(tee -a "$BIG_BENCH_DATAGEN_STAGE_LOG") 2>&1
 	rc=$?
 	if [[ $rc != 0 ]] ; then
 		echo "Error executing data generation job"
+		return $rc
+	fi
+
+	echo hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec java ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 1 -o "'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@"
+
+	time (hadoop jar "${BIG_BENCH_TOOLS_DIR}/HadoopClusterExec.jar" -archives "${PDGF_ARCHIVE_PATH}" -execCWD "${PDGF_DISTRIBUTED_NODE_DIR}" ${HadoopClusterExecOptions} -exec java ${BIG_BENCH_HADOOP_DATAGEN_JVM_ENV} -cp "${HADOOP_CP}:pdgf.jar" ${PDGF_CLUSTER_CONF} pdgf.Controller -nc HadoopClusterExec.tasks -nn HadoopClusterExec.taskNumber -ns -c -sp REFRESH_PHASE 1 -o "'${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}/'+table.getName()+'/'" ${BIGBENCH_DATAGEN_HADOOP_OPTIONS} -s ${BIGBENCH_TABLES} ${PDGF_OPTIONS} "$@" ; echo  "======= Generating data time =========") > >(tee -a "$BIG_BENCH_DATAGEN_STAGE_LOG") 2>&1
+	rc=$?
+	if [[ $rc != 0 ]] ; then
+		echo "Error executing refresh data generation job"
 		return $rc
 	fi
 
@@ -107,6 +137,7 @@ exechadoopDataGen () {
 	echo "==============================================="
 	echo "Hadoop data generation job finished. "
 	echo "logs: ${BIG_BENCH_DATAGEN_STAGE_LOG}"
-	echo "View generated files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_DATA_DIR}"
+	echo "View generated files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_INIT_DATA_DIR}"
+	echo "View generated refresh files: hadoop fs -ls ${BIG_BENCH_HDFS_ABSOLUTE_REFRESH_DATA_DIR}"
 	echo "==============================================="
 }
