option to generate data only for selected tables

diff --git a/scripts/modules/populateMetastore b/scripts/modules/populateMetastore
--- a/scripts/modules/populateMetastore
+++ b/scripts/modules/populateMetastore
@@ -2,8 +2,13 @@
 
 populateMetastore () {
   "$BIG_BENCH_BASH_SCRIPT_DIR/bigBench" $LIST_OF_USER_OPTIONS cleanMetastore
-  runHiveCmd -f "$GLOBAL_POPULATE_FILE"
-
+  
+  if ! runHiveCmd -f "$GLOBAL_POPULATE_FILE"
+  then
+    echo "ERROR! something went wrong during population of metastore. See: $BIG_BENCH_LOADING_STAGE_LOG"
+    exit 1
+  fi
+  
   hadoop fs -mkdir -p "$BIG_BENCH_HDFS_ABSOLUTE_TEMP_DIR" &
   hadoop fs -mkdir -p "$BIG_BENCH_HDFS_ABSOLUTE_QUERY_RESULT_DIR" &
   wait
